#define BIT0   1
#define BIT1   2
#define BIT2   4
#define BIT3   8
#define BIT4  16
#define BIT5  32
#define BIT6  64
#define BIT7 128

#define ENC_TILE_PLAYERSTART(startposition) startposition
#define ENC_TILE_SPOT(offset, length) (64|(offset<<2)|(length-1))
#define ENC_TILE_BOX(offset, length) (128|(offset<<2)|(length-1))
#define ENC_TILE_BOX_SPOT(offset, length) (128|64|(offset<<2)|(length-1))
#define ENC_TILE_WALL(offset, length) (32|(offset<<2)|(length-1))
#define ENC_TILE_SPACE(length) (length-1)
#define ENC_LEVEL(x, y) (x>0?x<<4:x*-1<<4|128)|(y>0?y&(BIT2|BIT1|BIT0):y*-1&(BIT2|BIT1|BIT0)|BIT3)
#define ENC_LEVEL_END 0

unsigned char  CompressedLevelData[]=
{
	// Level 1, 14 bytes
	ENC_LEVEL(+2, +2), ENC_LEVEL(+3, +2), ENC_LEVEL(-2, +3), 
		ENC_LEVEL(-2, -2), ENC_LEVEL(-3, -2), ENC_LEVEL(+2, -3),
		ENC_TILE_PLAYERSTART(120), 
		ENC_TILE_SPOT( 0,  1), ENC_TILE_BOX(  1,  1), ENC_TILE_BOX(  1,  1), 
		ENC_TILE_SPOT( 0,  2), ENC_TILE_BOX(  1,  2), ENC_TILE_SPOT( 0,  1),
		ENC_LEVEL_END,

		// Level 2, 16 bytes (30)
		ENC_LEVEL(+4, +4), ENC_LEVEL(+2, -2), ENC_LEVEL(+2, +5), 
		ENC_LEVEL(-3, +1), ENC_LEVEL(-4, -4), ENC_LEVEL(-1, -4),
		ENC_TILE_PLAYERSTART(52),
		ENC_TILE_BOX(  3,  2), ENC_TILE_BOX(  1,  1), ENC_TILE_SPOT( 1,  1), 
		ENC_TILE_WALL( 0,  1), ENC_TILE_SPOT( 1,  1), ENC_TILE_WALL( 0,  1), 
		ENC_TILE_SPOT( 4,  1), ENC_TILE_WALL( 3,  1),
		ENC_LEVEL_END,

		// Level 3, 17 bytes (500b c boundary) (47)
		ENC_LEVEL(+6, +1), ENC_LEVEL(+2, +3), ENC_LEVEL(-1, +2), 
		ENC_LEVEL(-7, -1), ENC_LEVEL(-1, -3), ENC_LEVEL(+1, -2),
		ENC_TILE_PLAYERSTART(101),
		ENC_TILE_BOX(  5,  1), ENC_TILE_WALL( 0,  3), ENC_TILE_BOX(  5,  1), 
		ENC_TILE_BOX(  2,  1), ENC_TILE_SPOT( 2,  2), ENC_TILE_WALL( 0,  1), 
		ENC_TILE_BOX(  1,  1), ENC_TILE_SPOT( 1,  2), ENC_TILE_WALL( 0,  1),
		ENC_LEVEL_END,

		// Level 4, 16 bytes (63)
		ENC_LEVEL(+3, +3), ENC_LEVEL(+1, +4), ENC_LEVEL(-5, -6), 
		ENC_LEVEL(+1, -1), 
		ENC_TILE_PLAYERSTART(86),
		ENC_TILE_BOX(   2, 1), ENC_TILE_WALL(  1,  1), ENC_TILE_BOX(      0,  1),
		ENC_TILE_WALL(  1, 1), ENC_TILE_BOX(   1,  1), ENC_TILE_SPOT(     1,  1),
		ENC_TILE_BOX(   0, 1), ENC_TILE_SPOT(  2,  2), ENC_TILE_BOX_SPOT( 0,  1), 
		ENC_TILE_SPOT(  0, 1),
		ENC_LEVEL_END,

		// Level 5, 19 bytes (82)
		ENC_LEVEL(+4, +1), ENC_LEVEL(+1, +2), ENC_LEVEL(+1, +4), 
		ENC_LEVEL(-7, -4), ENC_LEVEL(+1, -3),
		ENC_TILE_PLAYERSTART(70),
		ENC_TILE_WALL(1, 1), ENC_TILE_BOX( 1, 1), ENC_TILE_WALL(2, 1), 
		ENC_TILE_WALL(1, 1), ENC_TILE_SPOT(1, 1), ENC_TILE_WALL(0, 1),
		ENC_TILE_WALL(1, 1), ENC_TILE_SPOT(2, 1), ENC_TILE_BOX( 0, 1), 
		ENC_TILE_WALL(2, 1), ENC_TILE_SPOT(1, 1), ENC_TILE_BOX( 3, 1),
		ENC_LEVEL_END,

		// Level 6, 33 bytes (115)
		ENC_LEVEL(+6, +3), ENC_LEVEL(+1, +4), ENC_LEVEL(+2, +3), 
		ENC_LEVEL(-7,  0), ENC_LEVEL(-4, -3), ENC_LEVEL(-1, -6),
		ENC_LEVEL(+3, -1),
		ENC_TILE_PLAYERSTART(156),
		ENC_TILE_SPOT( 8, 1), ENC_TILE_WALL(    0, 3), ENC_TILE_WALL(2, 1),
		ENC_TILE_WALL( 1, 1), ENC_TILE_WALL(    5, 1), ENC_TILE_BOX( 1, 1), 
		ENC_TILE_BOX(  1, 1), ENC_TILE_WALL(    0, 1), ENC_TILE_SPOT(0, 1), 
		ENC_TILE_WALL( 2, 1), ENC_TILE_BOX_SPOT(2, 1), ENC_TILE_WALL(2, 1),
		ENC_TILE_SPOT( 2, 1), ENC_TILE_WALL(    0, 1), ENC_TILE_BOX( 0, 1), 
		ENC_TILE_BOX(  1, 1), ENC_TILE_WALL(    1, 1), ENC_TILE_WALL(5, 1), 
		ENC_TILE_WALL( 1, 1), ENC_TILE_WALL(    2, 3), ENC_TILE_SPOT(0, 1), 
		ENC_TILE_SPACE(9   ), ENC_TILE_WALL(    0, 2),
		ENC_LEVEL_END,

		// Level 7, 19 bytes (134)
		ENC_LEVEL(+6, +5), ENC_LEVEL(-1, +2), ENC_LEVEL(-7,  0), 
		ENC_LEVEL(-1, -2), ENC_LEVEL(+2, -4), ENC_LEVEL(+1, -1),
		ENC_TILE_PLAYERSTART(75),
		ENC_TILE_WALL(2, 1), ENC_TILE_WALL(4, 1), ENC_TILE_BOX( 2, 1), 
		ENC_TILE_BOX( 1, 1), ENC_TILE_BOX( 1, 1), ENC_TILE_BOX( 2, 1),
		ENC_TILE_WALL(0, 2), ENC_TILE_BOX( 3, 1), ENC_TILE_WALL(1, 1),
		ENC_TILE_SPOT(1, 4), ENC_TILE_SPOT(0, 1),
		ENC_LEVEL_END,

		// Level 8, 18 bytes (152)
		ENC_LEVEL(+5, +2), ENC_LEVEL(+1, +2), ENC_LEVEL(-1, +2), 
		ENC_LEVEL(-3, -1), ENC_LEVEL(-5, -3), ENC_LEVEL(+1, -1),
		ENC_LEVEL(+2, -1),
		ENC_TILE_PLAYERSTART(107),
		ENC_TILE_SPOT(4, 1), ENC_TILE_BOX(1, 1), ENC_TILE_WALL(0, 2),
		ENC_TILE_SPOT(1, 2), ENC_TILE_BOX(0, 1), ENC_TILE_BOX( 1, 1),
		ENC_TILE_SPOT(2, 2), ENC_TILE_BOX(1, 1), ENC_TILE_BOX( 1, 1),
		ENC_LEVEL_END,

		// Level 9, 23 bytes (175)
		ENC_LEVEL(+7,  0), ENC_LEVEL(+1, +5), ENC_LEVEL(+1, +3), 
		ENC_LEVEL(-7,  0), ENC_LEVEL(-3, -3), ENC_LEVEL(+1, -5),
		ENC_TILE_PLAYERSTART(154),
		ENC_TILE_WALL(2, 2), ENC_TILE_BOX( 6, 1), ENC_TILE_BOX( 3, 1),
		ENC_TILE_WALL(1, 3), ENC_TILE_BOX( 1, 1), ENC_TILE_WALL(1, 1),
		ENC_TILE_SPOT(0, 3), ENC_TILE_WALL(0, 1), ENC_TILE_WALL(2, 1),
		ENC_TILE_SPOT(0, 3), ENC_TILE_WALL(0, 1), ENC_TILE_BOX( 2, 1),
		ENC_TILE_BOX( 2, 1), ENC_TILE_BOX( 2, 1), ENC_TILE_WALL(6, 1),
		ENC_LEVEL_END,

		// Level 10, 12 bytes (187)
		ENC_LEVEL(+5, +4), ENC_LEVEL(-1, +2), ENC_LEVEL(-3, -1), 
		ENC_LEVEL(-3, -3), ENC_LEVEL(+2, -2),
		ENC_TILE_PLAYERSTART(101),
		ENC_TILE_BOX(4, 3), ENC_TILE_BOX( 2, 1), ENC_TILE_SPOT(0, 2),
		ENC_TILE_BOX(2, 1), ENC_TILE_SPOT(0, 3),
		ENC_LEVEL_END,

		// Level 11, 16 bytes (203)
		ENC_LEVEL(+3, +2), ENC_LEVEL(+3, -2), ENC_LEVEL(+4, +4), 
		ENC_LEVEL(-1, +1), ENC_LEVEL(-7,  0), ENC_LEVEL(-2, -1),
		ENC_LEVEL(-1, -3), ENC_LEVEL( 1, -1),
		ENC_TILE_PLAYERSTART(138),
		ENC_TILE_BOX( 6, 1), ENC_TILE_BOX(1, 1), ENC_TILE_BOX( 4, 1),
		ENC_TILE_SPOT(0, 4), ENC_TILE_BOX(1, 1), ENC_TILE_WALL(5, 1),
		ENC_LEVEL_END,

		// Level 12, 15 bytes (218) (500b c boundary)
		ENC_LEVEL(+4, +2), ENC_LEVEL(+1, +3), ENC_LEVEL(-1, +1), 
		ENC_LEVEL(-4, -2), ENC_LEVEL(-2, -3), ENC_LEVEL(+2, -1),
		ENC_TILE_PLAYERSTART(73),
		ENC_TILE_BOX(4, 1), ENC_TILE_SPOT(0, 1), ENC_TILE_SPOT(    3, 1), 
		ENC_TILE_BOX(0, 1), ENC_TILE_SPOT(0, 1), ENC_TILE_BOX_SPOT(2, 1), 
		ENC_TILE_BOX(0, 1),
		ENC_LEVEL_END,

		// Level 13, 15 bytes (233)
		ENC_LEVEL(+3, +2), ENC_LEVEL(+1, +2), ENC_LEVEL(+1, +3), 
		ENC_LEVEL(-7, -3), ENC_LEVEL(+1, -2), ENC_LEVEL(+1, -2),
		ENC_TILE_PLAYERSTART(151),
		ENC_TILE_SPOT(0, 2), ENC_TILE_SPOT(1, 1), ENC_TILE_BOX( 2, 1), 
		ENC_TILE_SPOT(0, 1), ENC_TILE_BOX( 1, 1), ENC_TILE_WALL(4, 1), 
		ENC_TILE_BOX( 0, 2),
		ENC_LEVEL_END,

		// Level 14, 16 bytes (249)
		ENC_LEVEL(+7, +6), ENC_LEVEL(-7, -6),
		ENC_TILE_PLAYERSTART(101),
		ENC_TILE_WALL(    2, 1), ENC_TILE_BOX( 4, 1), ENC_TILE_SPOT(0, 2), 
		ENC_TILE_BOX(     0, 1), ENC_TILE_BOX( 1, 1), ENC_TILE_SPOT(0, 1),
		ENC_TILE_BOX_SPOT(0, 1), ENC_TILE_WALL(1, 1), ENC_TILE_BOX( 1, 1), 
		ENC_TILE_SPOT(    0, 2), ENC_TILE_BOX( 0, 1), ENC_TILE_WALL(3, 1),
		ENC_LEVEL_END,

		// Level 15, 14 bytes (263)
		ENC_LEVEL(+5, +1), ENC_LEVEL(+1, +4), ENC_LEVEL(-2, +1),
		ENC_LEVEL(-3, -1), ENC_LEVEL(-2, -4), ENC_LEVEL(+1, -1),
		ENC_TILE_PLAYERSTART(136),
		ENC_TILE_BOX( 5, 1), ENC_TILE_BOX(1, 2), ENC_TILE_SPOT(1, 4), 
		ENC_TILE_SPOT(0, 2), ENC_TILE_BOX(1, 2), ENC_TILE_BOX( 1, 1),
		ENC_LEVEL_END,

		// Level 16, 19 bytes (282)
		ENC_LEVEL(+5, +1), ENC_LEVEL(+2, +7), ENC_LEVEL(-6, -2),
		ENC_LEVEL(-3, -3), ENC_LEVEL(+2, -3), 
		ENC_TILE_PLAYERSTART(153),
		ENC_TILE_BOX( 5, 1), ENC_TILE_BOX( 5, 1), ENC_TILE_WALL(1, 2), 
		ENC_TILE_SPOT(1, 3), ENC_TILE_BOX( 1, 1), ENC_TILE_SPOT(3, 3),
		ENC_TILE_BOX( 0, 1), ENC_TILE_WALL(0, 1 ),ENC_TILE_BOX( 0, 1),
		ENC_TILE_WALL(1, 1), ENC_TILE_WALL(1, 1), ENC_TILE_BOX( 1, 1),
		ENC_LEVEL_END,

		// Level 17, 12 bytes (294)
		ENC_LEVEL(+5, +2), ENC_LEVEL(+1, +1), ENC_LEVEL(+2, +3),
		ENC_LEVEL(-7, -2), ENC_LEVEL(-1, -4), 
		ENC_TILE_PLAYERSTART(138),
		ENC_TILE_BOX( 5, 3), ENC_TILE_WALL(2, 1), ENC_TILE_SPOT(0, 2), 
		ENC_TILE_SPOT(2, 2), ENC_TILE_BOX( 0, 1), 
		ENC_LEVEL_END,

		// Level 18, 23 bytes (317)
		ENC_LEVEL(+7, +7), ENC_LEVEL( 0, +1), ENC_LEVEL(-3, -1),
		ENC_LEVEL(-6, -3), ENC_LEVEL(+1, -2), ENC_LEVEL(+1, -2), 
		ENC_TILE_PLAYERSTART(137),
		ENC_TILE_WALL(    3, 1), ENC_TILE_SPOT(0, 1), ENC_TILE_BOX( 3, 1), 
		ENC_TILE_SPOT(    0, 3), ENC_TILE_BOX( 2, 1), ENC_TILE_WALL(1, 1),
		ENC_TILE_BOX_SPOT(0, 1), ENC_TILE_SPOT(0, 1), ENC_TILE_WALL(1, 2),
		ENC_TILE_BOX(     0, 1), ENC_TILE_WALL(0, 1), ENC_TILE_WALL(1, 1),
		ENC_TILE_BOX(     3, 1), ENC_TILE_BOX( 2, 1), ENC_TILE_WALL(4, 1),
		ENC_LEVEL_END,

		// Level 19, 20 bytes (337)
		ENC_LEVEL(+6, +2), ENC_LEVEL(+2, +4), ENC_LEVEL(-2, +1),
		ENC_LEVEL(-4, -1), ENC_LEVEL(-3, -4), ENC_LEVEL(+1, -2), 
		ENC_TILE_PLAYERSTART(152),
		ENC_TILE_SPOT(0, 4), ENC_TILE_WALL(1, 1), ENC_TILE_SPOT(0, 3),
		ENC_TILE_BOX( 0, 1), ENC_TILE_BOX( 2, 1), ENC_TILE_WALL(0, 1),
		ENC_TILE_BOX( 0, 1), ENC_TILE_BOX( 1, 1), ENC_TILE_BOX( 2, 2),
		ENC_TILE_WALL(2, 1), ENC_TILE_BOX( 0, 1), ENC_TILE_WALL(5, 1),
		ENC_LEVEL_END,

		// Level 20, 14 bytes (351)
		ENC_LEVEL(+6, +7), ENC_LEVEL(-6, -7),
		ENC_TILE_PLAYERSTART(152),
		ENC_TILE_SPOT(0, 2), ENC_TILE_BOX( 0, 1), ENC_TILE_SPOT(0, 2),
		ENC_TILE_SPOT(0, 2), ENC_TILE_WALL(0, 1), ENC_TILE_SPOT(0, 2),
		ENC_TILE_BOX( 1, 3), ENC_TILE_BOX( 3, 1), ENC_TILE_BOX( 3, 3),
		ENC_TILE_WALL(3, 1), 
		ENC_LEVEL_END,

		// Level 21, 17 bytes (368)
		ENC_LEVEL(+5, +3), ENC_LEVEL(+2, +4), ENC_LEVEL(-4, -1), 
		ENC_LEVEL(-2, +1), ENC_LEVEL(-4, -5), ENC_LEVEL(+3, -2),
		ENC_TILE_PLAYERSTART(131),
		ENC_TILE_SPOT(1, 3), ENC_TILE_SPOT(0, 4), ENC_TILE_WALL(2, 3),
		ENC_TILE_BOX( 0, 1), ENC_TILE_BOX( 2, 1), ENC_TILE_BOX( 1, 1),
		ENC_TILE_BOX( 2, 2), ENC_TILE_BOX( 2, 1), ENC_TILE_BOX( 1, 1),
		ENC_LEVEL_END,

		// Level 22, 17 bytes (385)
		ENC_LEVEL(+7, +4), ENC_LEVEL(+1, +4), ENC_LEVEL(-7, -4), 
		ENC_LEVEL(-1, -4), 
		ENC_TILE_PLAYERSTART(154),
		ENC_TILE_WALL(7, 1), ENC_TILE_BOX( 0, 2), ENC_TILE_SPOT(3, 3),
		ENC_TILE_WALL(0, 1), ENC_TILE_SPOT(1, 3), ENC_TILE_BOX( 0, 1),
		ENC_TILE_WALL(2, 2), ENC_TILE_BOX( 1, 1), ENC_TILE_BOX( 1, 1),
		ENC_TILE_BOX( 2, 1), ENC_TILE_WALL(4, 1),
		ENC_LEVEL_END,

		// Level 23, 16 bytes (401)
		ENC_LEVEL(+4, +1), ENC_LEVEL(+3, +3), ENC_LEVEL(-2, +3), 
		ENC_LEVEL(-5, -3), ENC_LEVEL(-2, -3), ENC_LEVEL(+2, -1), 
		ENC_TILE_PLAYERSTART(107),
		ENC_TILE_BOX( 6, 1), ENC_TILE_BOX( 1, 1), ENC_TILE_BOX( 3, 1),
		ENC_TILE_BOX( 3, 1), ENC_TILE_BOX( 1, 2), ENC_TILE_WALL( 0, 2),
		ENC_TILE_SPOT(2, 2), ENC_TILE_SPOT(0, 4),
		ENC_LEVEL_END,

		// Level 24, 32 bytes (433)
		ENC_LEVEL(+5, +1), ENC_LEVEL(+2, +2), ENC_LEVEL(+2, -3), 
		ENC_LEVEL(+4, +7), ENC_LEVEL( 0, +1), ENC_LEVEL(-7,  0), 
		ENC_LEVEL(-3, -1), ENC_LEVEL(-1, -2), ENC_LEVEL(-2, -5), 
		ENC_TILE_PLAYERSTART(108),
		ENC_TILE_SPOT(6, 1), ENC_TILE_BOX( 2, 1), ENC_TILE_BOX( 1, 1),
		ENC_TILE_SPOT(1, 3), ENC_TILE_WALL(1, 1), ENC_TILE_BOX( 2, 1),
		ENC_TILE_SPOT(3, 1), ENC_TILE_BOX( 2, 3), ENC_TILE_BOX( 3, 1),
		ENC_TILE_SPOT(1, 1), ENC_TILE_BOX( 2, 1), ENC_TILE_BOX( 2, 1),
		ENC_TILE_WALL(0, 1), ENC_TILE_SPOT(2, 1), ENC_TILE_BOX( 2, 1),
		ENC_TILE_WALL(0, 1), ENC_TILE_BOX( 0, 1), ENC_TILE_WALL(1, 1),
		ENC_TILE_SPOT(0, 3), ENC_TILE_WALL(5, 1), ENC_TILE_SPOT(2, 1),
		ENC_LEVEL_END,

		// Level 25, 28 bytes (461)
		ENC_LEVEL(+5, +7), ENC_LEVEL( 0, +1), ENC_LEVEL(-6, +1), 
		ENC_LEVEL(-4, -4), ENC_LEVEL(+1, -4), ENC_LEVEL(+4, -1), 
		ENC_TILE_PLAYERSTART(163),
		ENC_TILE_SPOT(0, 1), ENC_TILE_WALL(5, 1), ENC_TILE_SPOT(0, 2),
		ENC_TILE_WALL(0, 2), ENC_TILE_BOX( 3, 1), ENC_TILE_SPOT(0, 2),
		ENC_TILE_WALL(5, 1), ENC_TILE_SPOT(1, 1), ENC_TILE_WALL(0, 1),
		ENC_TILE_WALL(1, 1), ENC_TILE_WALL(0, 1), ENC_TILE_WALL(1, 2),
		ENC_TILE_BOX( 0, 1), ENC_TILE_WALL(0, 1), ENC_TILE_BOX( 3, 1),
		ENC_TILE_BOX( 4, 2), ENC_TILE_WALL(2, 1), ENC_TILE_BOX( 0, 1),
		ENC_TILE_WALL(0, 1), ENC_TILE_WALL(2, 1), 
		ENC_LEVEL_END,

		// Level 26, 33 bytes (494)
		ENC_LEVEL(+7,  0), ENC_LEVEL(+1, +1), ENC_LEVEL(+3, +3), 
		ENC_LEVEL(-1, +5), ENC_LEVEL(-3, +2), ENC_LEVEL(-4, -2), 
		ENC_LEVEL(-4, -3), ENC_LEVEL(+1, -6), 
		ENC_TILE_PLAYERSTART(155),
		ENC_TILE_WALL(3, 2), ENC_TILE_BOX( 3, 1), ENC_TILE_SPACE(   8   ), 
		ENC_TILE_WALL(0, 1), ENC_TILE_BOX( 0, 1), ENC_TILE_WALL(    0, 3), 
		ENC_TILE_WALL(1, 2), ENC_TILE_WALL(4, 2), ENC_TILE_BOX_SPOT(1, 1), 
		ENC_TILE_WALL(1,1),	 ENC_TILE_BOX( 2, 1), ENC_TILE_SPOT(    0, 4), 
		ENC_TILE_SPOT(0, 2), ENC_TILE_WALL(2, 3), ENC_TILE_SPOT(    1, 1), 
		ENC_TILE_WALL(1, 1), ENC_TILE_BOX( 6, 1), ENC_TILE_WALL(    0, 3), 
		ENC_TILE_BOX( 0, 1), ENC_TILE_WALL(3, 1), ENC_TILE_BOX(     4, 1), 
		ENC_TILE_BOX( 0, 1), ENC_TILE_WALL(0, 1),
		ENC_LEVEL_END,

		// Level 27, 39 bytes (533)
		ENC_LEVEL(+7,  0), ENC_LEVEL(+1, +7), ENC_LEVEL(-3, +3), 
		ENC_LEVEL(-2, +1), ENC_LEVEL(-4, -1), ENC_LEVEL(-2, +1), 
		ENC_LEVEL(-3, -7), ENC_LEVEL(+6, -4), 
		ENC_TILE_PLAYERSTART(183),
		ENC_TILE_SPACE(7   ), ENC_TILE_WALL(1, 1), ENC_TILE_WALL(1 ,1),
		ENC_TILE_WALL( 1, 1), ENC_TILE_BOX( 3, 1), ENC_TILE_BOX( 1, 1), 
		ENC_TILE_WALL( 0, 1), ENC_TILE_BOX( 4, 1), ENC_TILE_SPOT(3, 2),
		ENC_TILE_WALL( 0, 1), ENC_TILE_WALL(2, 2), ENC_TILE_BOX( 1, 1), 
		ENC_TILE_BOX(  1, 1), ENC_TILE_WALL(0, 1), ENC_TILE_SPOT(1, 2), 
		ENC_TILE_WALL( 3, 2), ENC_TILE_BOX( 1, 1), ENC_TILE_BOX( 1, 1),
		ENC_TILE_SPOT( 2, 2), ENC_TILE_WALL(0, 1), ENC_TILE_WALL(2, 2), 
		ENC_TILE_WALL( 1, 2), ENC_TILE_SPOT(0, 2), ENC_TILE_WALL(0, 1), 
		ENC_TILE_WALL( 1, 1), ENC_TILE_BOX( 1, 1), ENC_TILE_BOX( 1, 1), 
		ENC_TILE_SPOT( 1, 2), ENC_TILE_BOX( 5, 1),
		ENC_LEVEL_END,

		// Level 28, 66 bytes (599)
		ENC_LEVEL(+3, +4), ENC_LEVEL(+2, -2), ENC_LEVEL(+6, +4), 
		ENC_LEVEL( 0, +4), ENC_LEVEL(-6, -2), ENC_LEVEL(-2, +4), 
		ENC_LEVEL(-3, -1), ENC_LEVEL(-4, -3), ENC_LEVEL(+1, -4),
		ENC_LEVEL(-1, -3), ENC_LEVEL(+4, -1),
		ENC_TILE_PLAYERSTART(98),
		ENC_TILE_BOX(     4, 1), ENC_TILE_BOX     (1, 1), ENC_TILE_BOX(     4, 1),
		ENC_TILE_BOX_SPOT(2, 1), ENC_TILE_SPOT    (0, 1), ENC_TILE_BOX_SPOT(0, 1),
		ENC_TILE_SPOT(    0, 1), ENC_TILE_BOX_SPOT(0, 1), ENC_TILE_BOX(     1, 1),
		ENC_TILE_BOX(     1, 1), ENC_TILE_SPOT    (1, 1), ENC_TILE_BOX_SPOT(0, 1), 
		ENC_TILE_SPOT(    0, 1), ENC_TILE_BOX_SPOT(0, 1), ENC_TILE_SPOT(    0, 1),
		ENC_TILE_BOX(     0, 1), ENC_TILE_BOX(     1, 1), ENC_TILE_WALL(    2, 1),
		ENC_TILE_BOX_SPOT(2, 1), ENC_TILE_SPOT(    0, 1), ENC_TILE_BOX_SPOT(0, 1),
		ENC_TILE_SPOT(    0, 1), ENC_TILE_BOX_SPOT(0, 1), ENC_TILE_BOX(     0, 1),
		ENC_TILE_BOX(     1, 1), ENC_TILE_SPOT(    4, 1), ENC_TILE_BOX_SPOT(0, 1),
		ENC_TILE_SPOT(    0, 1), ENC_TILE_BOX_SPOT(0, 1), ENC_TILE_WALL(    0, 1),
		ENC_TILE_BOX(     0, 1), ENC_TILE_BOX(     1, 1), ENC_TILE_WALL(    2, 1),
		ENC_TILE_BOX_SPOT(2, 1), ENC_TILE_SPOT(    0, 1), ENC_TILE_BOX_SPOT(0, 1),
		ENC_TILE_SPOT(    0, 1), ENC_TILE_BOX_SPOT(0, 1), ENC_TILE_BOX(     1, 1),
		ENC_TILE_BOX(     1, 1), ENC_TILE_SPOT(    1, 1), ENC_TILE_BOX_SPOT(0, 1),
		ENC_TILE_SPOT(    0, 1), ENC_TILE_BOX_SPOT(0, 1), ENC_TILE_SPOT(    0, 1),
		ENC_TILE_BOX(     3, 1), ENC_TILE_BOX_SPOT(2, 1), ENC_TILE_SPOT(    0, 1),
		ENC_TILE_BOX_SPOT(0, 1), ENC_TILE_SPOT(    0, 1), ENC_TILE_BOX_SPOT(0, 1),
		ENC_TILE_BOX(     2, 1), ENC_TILE_BOX(     1, 1),
		ENC_LEVEL_END,

		// Level 29, 15 bytes (627)
		ENC_LEVEL(+7, +2), ENC_LEVEL(+1, +4), ENC_LEVEL(-7, -2), 
		ENC_LEVEL(-1, -4), 
		ENC_TILE_PLAYERSTART(135),
		ENC_TILE_SPOT(0, 4), ENC_TILE_SPOT(0, 2), ENC_TILE_BOX( 2, 1), 
		ENC_TILE_WALL(1, 1), ENC_TILE_BOX( 2, 1), ENC_TILE_WALL(1, 1),
		ENC_TILE_BOX( 1, 1), ENC_TILE_BOX( 1, 1), ENC_TILE_BOX( 1, 1),
		ENC_TILE_BOX( 1, 1),
		ENC_LEVEL_END,

		// Level 30, 23 bytes (650)
		ENC_LEVEL(+7,  0), ENC_LEVEL(+2, +3), ENC_LEVEL(-1, +3), 
		ENC_LEVEL(-7,  0), ENC_LEVEL(-2, -2), ENC_LEVEL(-1, -3),
		ENC_LEVEL(+2, -1),
		ENC_TILE_PLAYERSTART(100),
		ENC_TILE_SPOT(3, 1), ENC_TILE_WALL(7, 2), ENC_TILE_BOX( 0, 1),
		ENC_TILE_WALL(0, 2), ENC_TILE_BOX( 3, 1), ENC_TILE_SPOT(0, 1),
		ENC_TILE_SPOT(1, 1), ENC_TILE_SPOT(1, 1), ENC_TILE_BOX( 0, 1),
		ENC_TILE_BOX( 1, 1), ENC_TILE_WALL(0, 2), ENC_TILE_BOX( 0, 1),
		ENC_TILE_WALL(0, 2), ENC_TILE_SPOT(5, 1),
		ENC_LEVEL_END,

		// Level 31, 18 bytes (668)
		ENC_LEVEL(+5, +5), ENC_LEVEL(-1, +2), ENC_LEVEL(-4, -1), 
		ENC_LEVEL(-3, -5), ENC_LEVEL(+3, -1),
		ENC_TILE_PLAYERSTART(74),
		ENC_TILE_SPOT(0, 1), ENC_TILE_BOX( 4, 3), ENC_TILE_SPOT(2, 1),
		ENC_TILE_WALL(0, 2), ENC_TILE_SPOT(0, 1), ENC_TILE_WALL(0, 2),
		ENC_TILE_SPOT(0, 1), ENC_TILE_BOX( 3, 1), ENC_TILE_BOX( 5, 1), 
		ENC_TILE_SPOT(0, 1), ENC_TILE_WALL(0, 1),
		ENC_LEVEL_END,

		// Level 32, 17 bytes (685)
		ENC_LEVEL(+5, +3), ENC_LEVEL(+1, +4), ENC_LEVEL(-7, -4), 
		ENC_LEVEL(+1, -3), 
		ENC_TILE_PLAYERSTART(152),
		ENC_TILE_SPOT(0, 1), ENC_TILE_SPOT(1, 3), ENC_TILE_BOX( 1, 1),
		ENC_TILE_SPOT(0, 1), ENC_TILE_WALL(0, 1), ENC_TILE_BOX( 2, 1),
		ENC_TILE_BOX( 1, 1), ENC_TILE_BOX( 2, 1), ENC_TILE_WALL(2, 1),
		ENC_TILE_BOX( 0, 1), ENC_TILE_WALL(0, 2),
		ENC_LEVEL_END,

		// Level 33, 35 bytes (720)
		ENC_LEVEL(+5, +1), ENC_LEVEL(+2, +1), ENC_LEVEL(+2, +4), 
		ENC_LEVEL(-4, +2), ENC_LEVEL(-1, +3), ENC_LEVEL(-7,  0),
		ENC_LEVEL(-1, -5), ENC_LEVEL(+2, -5), ENC_LEVEL(+2, -1),
		ENC_TILE_PLAYERSTART(132),
		ENC_TILE_WALL(7, 1), ENC_TILE_BOX( 0, 1), ENC_TILE_BOX( 6, 1), 
		ENC_TILE_BOX( 3, 2), ENC_TILE_BOX( 2, 2), ENC_TILE_WALL(1, 1),
		ENC_TILE_BOX( 0, 1), ENC_TILE_WALL(4, 1), ENC_TILE_BOX( 3, 1), 
		ENC_TILE_BOX( 3 ,1), ENC_TILE_WALL(1, 3), ENC_TILE_WALL(1, 1),
		ENC_TILE_BOX( 0, 1), ENC_TILE_SPOT(0, 2), ENC_TILE_WALL(1, 1),
		ENC_TILE_BOX( 0, 1), ENC_TILE_SPOT(2, 1), ENC_TILE_WALL(0, 1), 
		ENC_TILE_SPOT(0, 2), ENC_TILE_BOX( 2, 1), ENC_TILE_SPOT(0, 4), 
		ENC_TILE_BOX( 0, 1), ENC_TILE_WALL(0, 1), ENC_TILE_SPOT(1, 4),
		ENC_LEVEL_END,

		// Level 34, 58 bytes (778)
		ENC_LEVEL(+7,  0), ENC_LEVEL(+7, +7), ENC_LEVEL(0, +5), 
		ENC_LEVEL(-7,  0), ENC_LEVEL(-7, -7), ENC_LEVEL(0, -5),
		ENC_TILE_PLAYERSTART(116),
		ENC_TILE_WALL(6, 1), ENC_TILE_BOX( 7, 1), ENC_TILE_WALL( 1, 1), 
		ENC_TILE_BOX( 0, 1), ENC_TILE_WALL(1, 1), ENC_TILE_BOX(  1, 1),
		ENC_TILE_WALL(0, 2), ENC_TILE_BOX( 0, 1), ENC_TILE_WALL( 2, 1), 
		ENC_TILE_BOX( 2, 1), ENC_TILE_WALL(1, 1), ENC_TILE_SPACE(9   ),
		ENC_TILE_WALL(0, 2), ENC_TILE_BOX( 0, 1), ENC_TILE_WALL( 0, 1),
		ENC_TILE_BOX( 0, 1), ENC_TILE_WALL(0, 2), ENC_TILE_BOX(  0, 2), 
		ENC_TILE_WALL(2, 1), ENC_TILE_WALL(1, 1), ENC_TILE_SPOT( 1, 3), 
		ENC_TILE_WALL(1, 1), ENC_TILE_BOX( 4, 1), ENC_TILE_SPOT( 2, 1),
		ENC_TILE_WALL(1, 1), ENC_TILE_SPOT(1, 1), ENC_TILE_BOX(  0, 1),
		ENC_TILE_WALL(1, 1), ENC_TILE_BOX( 2, 1), ENC_TILE_WALL( 0, 1),
		ENC_TILE_BOX( 0, 1), ENC_TILE_SPOT(0, 3), ENC_TILE_WALL( 0, 1),
		ENC_TILE_WALL(1, 1), ENC_TILE_SPOT(6, 1), ENC_TILE_WALL( 1, 1),
		ENC_TILE_SPOT(1, 1), ENC_TILE_BOX( 2, 1), ENC_TILE_WALL( 2, 2),
		ENC_TILE_SPOT(0, 1), ENC_TILE_BOX( 0, 1), ENC_TILE_WALL( 0, 3),
		ENC_TILE_BOX( 0, 1), ENC_TILE_SPOT(0, 1), ENC_TILE_WALL( 1 ,1),
		ENC_TILE_WALL(2, 1), ENC_TILE_BOX( 1, 1), ENC_TILE_SPOT( 0, 4),
		ENC_TILE_SPOT(0, 1), ENC_TILE_WALL(1, 2),
		ENC_LEVEL_END,

		// Level 35, 26 bytes (804)
		ENC_LEVEL(+7,  0), ENC_LEVEL(+1, +5), ENC_LEVEL(+1, +4), 
		ENC_LEVEL(-4, -1), ENC_LEVEL(-5, -7), ENC_LEVEL(0,  -1),
		ENC_TILE_PLAYERSTART(104),
		ENC_TILE_WALL( 3, 2), ENC_TILE_WALL(    3, 1), ENC_TILE_BOX( 1, 1),
		ENC_TILE_BOX(  1, 1), ENC_TILE_BOX_SPOT(3, 1), ENC_TILE_SPOT(0, 1),
		ENC_TILE_WALL( 0, 1), ENC_TILE_WALL(    2, 1), ENC_TILE_WALL(1, 1),
		ENC_TILE_SPOT( 0, 2), ENC_TILE_WALL(    0, 2), ENC_TILE_SPOT(0, 1),
		ENC_TILE_WALL( 0, 3), ENC_TILE_BOX_SPOT(0, 1), ENC_TILE_WALL(0, 1),
		ENC_TILE_SPACE(11  ), ENC_TILE_WALL(    0, 2), ENC_TILE_WALL(1, 1),
		ENC_LEVEL_END,

		// Level 36, 34 bytes (838)
		ENC_LEVEL(+7, +2), ENC_LEVEL(+2, +1), ENC_LEVEL(+4, +1), 
		ENC_LEVEL(+1, +3), ENC_LEVEL(-1, +4), ENC_LEVEL(-3, -1), 
		ENC_LEVEL(-7,  0), ENC_LEVEL(-3, -3), ENC_LEVEL(+1, -3), 
		ENC_LEVEL(-1, -4),
		ENC_TILE_PLAYERSTART(100),
		ENC_TILE_BOX( 7, 2), ENC_TILE_BOX( 5, 1), ENC_TILE_BOX( 1, 3),
		ENC_TILE_WALL(2, 2), ENC_TILE_SPOT(1, 3), ENC_TILE_WALL(5, 2),
		ENC_TILE_SPOT(0, 3), ENC_TILE_WALL(0, 3), ENC_TILE_BOX( 0, 1), 
		ENC_TILE_WALL(2, 1), ENC_TILE_BOX( 1, 1), ENC_TILE_SPOT(0, 3), 
		ENC_TILE_WALL(6, 1), ENC_TILE_BOX( 1, 1), ENC_TILE_SPOT(0, 3), 
		ENC_TILE_BOX( 0, 1), ENC_TILE_WALL(1, 1), ENC_TILE_WALL(3, 4), 
		ENC_TILE_WALL(0, 1), ENC_TILE_WALL(1, 3), ENC_TILE_BOX( 7, 1),
		ENC_TILE_BOX( 3, 1),
		ENC_LEVEL_END,

		// Level 37, 20 bytes (858)
		ENC_LEVEL(+4, +4), ENC_LEVEL(+1, +2), ENC_LEVEL(-1, +1),
		ENC_LEVEL(-7, -4), ENC_LEVEL(+3, -3),
		ENC_TILE_PLAYERSTART(72),
		ENC_TILE_BOX( 2, 3), ENC_TILE_SPOT(6, 1), ENC_TILE_WALL(0, 1),
		ENC_TILE_BOX( 0, 1), ENC_TILE_BOX( 1, 1), ENC_TILE_SPOT(0, 1),
		ENC_TILE_BOX( 0, 1), ENC_TILE_SPOT(0, 1), ENC_TILE_SPOT(1, 1),
		ENC_TILE_WALL(2, 1), ENC_TILE_SPOT(0, 1), ENC_TILE_WALL(0, 1),
		ENC_TILE_SPOT(0, 1),
		ENC_LEVEL_END,

		// Level 38, 33 bytes (891)
		ENC_LEVEL(+7,  0), ENC_LEVEL(+4, +7), ENC_LEVEL( 0, +4),
		ENC_LEVEL(-7,  0), ENC_LEVEL(-2, -2), ENC_LEVEL(-1, -3),
		ENC_LEVEL(-1, -6),
		ENC_TILE_PLAYERSTART(148),
		ENC_TILE_SPOT(0, 3), ENC_TILE_WALL(1, 1), ENC_TILE_SPOT(5, 2),
		ENC_TILE_WALL(2, 1), ENC_TILE_WALL(1, 2), ENC_TILE_SPOT(2, 2),
		ENC_TILE_WALL(5, 1), ENC_TILE_SPOT(2, 2), ENC_TILE_WALL(2, 1),
		ENC_TILE_BOX( 1, 1), ENC_TILE_WALL(0, 2), ENC_TILE_SPOT(1, 3),
		ENC_TILE_WALL(1, 1), ENC_TILE_BOX( 0, 1), ENC_TILE_BOX( 1, 1),
		ENC_TILE_WALL(2, 4), ENC_TILE_BOX( 2, 2), ENC_TILE_WALL(1, 1),
		ENC_TILE_BOX( 2, 1), ENC_TILE_BOX( 1, 2), ENC_TILE_BOX( 3, 3),
		ENC_TILE_WALL(2, 1), ENC_TILE_BOX( 2, 1), ENC_TILE_WALL(1, 2),
		ENC_LEVEL_END,

		// Level 39, 26 bytes (917)
		ENC_LEVEL(+7,  0), ENC_LEVEL(+1, +4), ENC_LEVEL(+1, +2),
		ENC_LEVEL(+1, +3), ENC_LEVEL(-7,  0), ENC_LEVEL(-1, -4),
		ENC_LEVEL(-1, -2), ENC_LEVEL(-1, -3),
		ENC_TILE_PLAYERSTART(165),
		ENC_TILE_BOX( 9, 1), ENC_TILE_BOX( 1, 1), ENC_TILE_BOX( 1, 1),
		ENC_TILE_WALL(1, 1), ENC_TILE_BOX( 0, 1), ENC_TILE_WALL(0, 2),
		ENC_TILE_SPOT(2, 2), ENC_TILE_SPOT(1, 2), ENC_TILE_SPOT(0, 2),
		ENC_TILE_SPOT(1, 2), ENC_TILE_WALL(2, 2), ENC_TILE_BOX( 0, 1),
		ENC_TILE_WALL(0, 1), ENC_TILE_BOX( 1, 1), ENC_TILE_BOX( 1, 1),
		ENC_TILE_BOX( 1, 1),
		ENC_LEVEL_END,

		// Level 40, 40 bytes (957) 
		ENC_LEVEL(+4, +1), ENC_LEVEL(+7, -1), ENC_LEVEL(+3, +4),
		ENC_LEVEL(-1, +4), ENC_LEVEL(-1, +4), ENC_LEVEL(-3, +1),
		ENC_LEVEL(-5, -4), ENC_LEVEL(-4, -3), ENC_LEVEL(+1, -4),
		ENC_LEVEL(-1, -2),
		ENC_TILE_PLAYERSTART(17),
		ENC_TILE_BOX(  5, 1), ENC_TILE_BOX( 7, 1), ENC_TILE_WALL(3, 1), 
		ENC_TILE_WALL( 1, 1), ENC_TILE_WALL(2, 4), ENC_TILE_BOX( 4, 1), 
		ENC_TILE_WALL( 3, 4), ENC_TILE_BOX( 0, 2), ENC_TILE_WALL(1, 2), 
		ENC_TILE_WALL( 1, 1), ENC_TILE_BOX( 1, 1), ENC_TILE_BOX( 1, 1), 
		ENC_TILE_BOX(  2, 1), ENC_TILE_BOX( 2, 1), ENC_TILE_WALL(0, 1), 
		ENC_TILE_SPACE(8   ), ENC_TILE_WALL(0, 1), ENC_TILE_WALL(6, 1), 
		ENC_TILE_WALL( 4, 4), ENC_TILE_WALL(0 ,1), ENC_TILE_BOX( 0, 1), 
		ENC_TILE_WALL( 0, 2), ENC_TILE_WALL(3, 1), ENC_TILE_SPOT(3, 3), 
		ENC_TILE_BOX(  2, 1), ENC_TILE_SPOT(1, 4), ENC_TILE_WALL(0, 1), 
		ENC_TILE_SPOT( 2, 4),
		ENC_LEVEL_END,

		// Level 41, 21 bytes (957) 
		ENC_LEVEL(+4, +4), ENC_LEVEL(-1, +3), ENC_LEVEL(-7,  0),
		ENC_LEVEL(-1, -3), ENC_LEVEL(+1, -3), ENC_LEVEL(+4, -1),
		ENC_TILE_PLAYERSTART(154),
		ENC_TILE_SPOT(    4 ,2), ENC_TILE_BOX( 1, 1), ENC_TILE_WALL(    0, 1), 
		ENC_TILE_WALL(    2, 1), ENC_TILE_SPOT(0, 1), ENC_TILE_BOX_SPOT(0, 1),
		ENC_TILE_BOX_SPOT(4, 1), ENC_TILE_SPOT(0, 1), ENC_TILE_WALL(    0, 1),
		ENC_TILE_BOX(     0, 1), ENC_TILE_BOX( 2, 1), ENC_TILE_BOX(     2, 1),
		ENC_TILE_WALL(    5, 2),
		ENC_LEVEL_END,

		// Level 42, 27 bytes
		ENC_LEVEL(+4, +1), ENC_LEVEL(+2, -1), ENC_LEVEL(+6, +7),
		ENC_LEVEL(-7, +1), ENC_LEVEL(-3, -2), ENC_LEVEL(-1, -3),
		ENC_LEVEL(-1, -3),
		ENC_TILE_PLAYERSTART(75),
		ENC_TILE_WALL(    5, 1), ENC_TILE_BOX( 3, 1), ENC_TILE_BOX( 5, 1),
		ENC_TILE_WALL(    3, 1), ENC_TILE_BOX( 0, 1), ENC_TILE_WALL(0, 2),
		ENC_TILE_SPOT(    0, 1), ENC_TILE_WALL(0, 2), ENC_TILE_SPOT(4, 3),
		ENC_TILE_BOX_SPOT(0, 1), ENC_TILE_SPOT(0, 1), ENC_TILE_BOX( 1, 1),
		ENC_TILE_BOX(     2, 1), ENC_TILE_WALL(0, 1), ENC_TILE_WALL(1, 1), 
		ENC_TILE_SPOT(    0, 1), ENC_TILE_WALL(0, 1), ENC_TILE_WALL(1, 1),
		ENC_TILE_BOX(     5, 1),
		ENC_LEVEL_END,

		// Level 43, 39 bytes
		ENC_LEVEL(+2, +1), ENC_LEVEL(+1, +1), ENC_LEVEL(+1, +4),
		ENC_LEVEL(+1, +3), ENC_LEVEL(-3, +2), ENC_LEVEL(-5, +1),
		ENC_LEVEL(-3, -2), ENC_LEVEL(-1, -1), ENC_LEVEL(-2, -3),
		ENC_LEVEL(+4, -5), ENC_LEVEL(+5, -1),
		ENC_TILE_PLAYERSTART(26),
		ENC_TILE_SPOT(0, 4), ENC_TILE_WALL(0, 1), ENC_TILE_BOX( 0, 1), 
		ENC_TILE_SPOT(1, 4), ENC_TILE_WALL(0, 1), ENC_TILE_BOX( 1, 1), 
		ENC_TILE_SPOT(1, 4), ENC_TILE_BOX( 1, 1), ENC_TILE_SPOT(3, 3),
		ENC_TILE_WALL(0, 1), ENC_TILE_WALL(3, 1), ENC_TILE_WALL(1, 4),
		ENC_TILE_WALL(0, 1), ENC_TILE_BOX( 2, 1), ENC_TILE_BOX( 1, 1),
		ENC_TILE_BOX( 3, 1), ENC_TILE_WALL(2, 1), ENC_TILE_BOX( 6, 2),
		ENC_TILE_BOX( 3, 1), ENC_TILE_BOX( 1, 1), ENC_TILE_BOX( 2, 1),
		ENC_TILE_BOX( 1, 1), ENC_TILE_BOX( 1, 1), ENC_TILE_BOX( 5, 1),
		ENC_TILE_BOX( 1, 1), 
		ENC_LEVEL_END,
		ENC_LEVEL_END,
};
